[package]
name = "twisted_cube_formalisation"
version = "0.1"
lean_version = "nightly-2018-11-13"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "c6a7f300ea43cfc0478e3ee81a141d5288d90df6"}
